name: CI/CD
on:
  push:
    branches: [ master ]
    
jobs:
  test_suite: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          python -m unittest discover src/tests/

  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with: 
          host: 52.1.10.76
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf website_availability_app
            git clone https://github.com/PandelisT/Website_Availability_Application.git
            python3.8 -m venv /home/github-actions/website_availability_app/venv
            source /home/github-actions/website_availability_app/venv/bin/activate
            pip install -r /home/github-actions/website_availability_app/requirements.txt
            
          
