name: CI/CD
on:
  push:
    branches: [ master ]
    
jobs:
  test_suite: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run tests
        run: |
          cd src && python -m unittest discover tests/

  deployment:
    needs: test_suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone & repo install
        uses: appleboy/ssh-action@master
        with: 
          host: 54.144.44.160
          username: github-actions
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            rm -rf Website_Availability_Application
            git clone https://github.com/PandelisT/Website_Availability_Application.git
            sudo apt-get install python3.8-venv
            sudo apt-get install nmap
            python3.8 -m venv /home/github-actions/Website_Availability_Application/venv
            source /home/github-actions/Website_Availability_Application/venv/bin/activate
            python -m pip install --upgrade pip setuptools wheel
            /home/github-actions/Website_Availability_Application/venv/bin/pip3.8 install -r /home/github-actions/Website_Availability_Application/requirements.txt
